from typing import Optional, List, Tuple
from datetime import timedelta

class Document:
    def __init__(self, id: str) -> None: ...
    def add_field(self, name: str, contents: str, index: bool) -> None: ...
    def size(self) -> int: ...

class Field:
    def __init__(self, name: str, contents: str) -> None: ...
    def name(self) -> str: ...
    def contents(self) -> str: ...

class SearchOperator:
    Or: SearchOperator
    And: SearchOperator

class RankingType:
    Tfidf: RankingType
    Bm25: RankingType

class SearchOptions:
    def __init__(
        self,
        include_documents: Optional[bool] = None,
        operator: Optional[SearchOperator] = None,
        ranking_type: Optional[RankingType] = None,
    ) -> None: ...

class PyVarro:
    def __init__(
        self,
        min_segment_size: Optional[int] = None,
        compaction_frequency: Optional[timedelta] = None,
        max_buffer_size: Optional[int] = None,
    ) -> None: ...
    def index(self, doc: Document) -> None: ...
    def index_size(self) -> int: ...
    def flush(self) -> None: ...
    def retrieve(self, id: str) -> Optional[Document]: ...
    def search(self, query: str, options: Optional[SearchOptions] = None) -> List[Tuple[Document, float]]: ...
